// src/utils/collegeData.ts

export const statesAndUTs = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Chandigarh",
  "Puducherry",
  "Jammu & Kashmir",
  "Ladakh",
  "Andaman & Nicobar Islands",
  "Dadra & Nagar Haveli and Daman & Diu",
  "Lakshadweep"
];

export const popularColleges = [
  "IIT Bombay (Indian Institute of Technology)",
  "IIT Delhi (Indian Institute of Technology)",
  "IIT Madras (Indian Institute of Technology)",
  "IIT Kharagpur (Indian Institute of Technology)",
  "IIT Kanpur (Indian Institute of Technology)",
  "IIT Roorkee (Indian Institute of Technology)",
  "IIT Guwahati (Indian Institute of Technology)",
  "IIT Hyderabad (Indian Institute of Technology)",
  "IIT BHU (Varanasi)",
  "NIT Trichy (National Institute of Technology)",
  "NIT Surathkal (National Institute of Technology)",
  "NIT Rourkela (National Institute of Technology)",
  "NIT Warangal (National Institute of Technology)",
  "NIT Calicut (National Institute of Technology)",
  "IIIT Allahabad (Indian Institute of Information Technology)",
  "IIIT Gwalior (Indian Institute of Information Technology)",
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Delhi",
  "BITS Pilani (Birla Institute of Technology and Science)",
  "BITS Goa",
  "BITS Hyderabad",
  "VIT Vellore (Vellore Institute of Technology)",
  "VIT Chennai",
  "VIT Bhopal",
  "SRM Institute of Science and Technology",
  "Christ University (Bangalore)",
  "Jain University (Bangalore)",
  "Presidency University (Bangalore)",
  "Manipal Academy of Higher Education (MAHE)",
  "Lovely Professional University (LPU)",
  "Amity University (Noida)",
  "Amity University (Mumbai)",
  "KIIT University (Kalinga Institute of Industrial Technology)",
  "UPES Dehradun",
  "Thapar Institute of Engineering and Technology",
  "Symbiosis International University",
  "NMIMS University (Mumbai)",
  "Delhi University (DU) - St. Stephen's College",
  "Delhi University (DU) - Hindu College",
  "Delhi University (DU) - Miranda House",
  "Delhi University (DU) - Hansraj College",
  "Delhi University (DU) - Shri Ram College of Commerce (SRCC)",
  "LSR (Lady Shri Ram College for Women)",
  "AIIMS New Delhi (All India Institute of Medical Sciences)",
  "AIIMS Rishikesh",
  "AIIMS Bhubaneswar",
  "JIPMER Puducherry",
  "King George's Medical University (KGMU)",
  "National Law School of India University (NLSIU Bangalore)",
  "NALSAR University of Law (Hyderabad)",
  "National Law University (NLU Delhi)",
  "National Institute of Design (NID Ahmedabad)",
  "National Institute of Fashion Technology (NIFT Delhi)",
  "Symbiosis Institute of Design (SID Pune)"
];

export const popularUniversities = [
  "Central Board of Secondary Education (CBSE)",
  "Delhi University (DU)",
  "Jawaharlal Nehru University (JNU)",
  "Banaras Hindu University (BHU)",
  "Aligarh Muslim University (AMU)",
  "Jamia Millia Islamia",
  "Indraprastha University (GGSIPU)",
  "Visva-Bharati University",
  "University of Mumbai",
  "Savitribai Phule Pune University",
  "University of Calcutta",
  "Anna University",
  "Bharathiar University",
  "University of Madras",
  "VTU (Visvesvaraya Technological University)",
  "Bangalore University",
  "Mysore University",
  "JNTU Hyderabad (Jawaharlal Nehru Technological University)",
  "Osmania University",
  "Andhra University",
  "AKTU Lucknow (Dr. A.P.J. Abdul Kalam Technical University)",
  "Lucknow University",
  "BHU Varanasi",
  "Biju Patnaik University of Technology (BPUT)",
  "Utkal University",
  "Rajasthan Technical University (RTU)",
  "Gujarat Technological University (GTU)",
  "MS University Baroda",
  "Punjab Technical University (PTU)",
  "Panjab University",
  "Calicut University",
  "Kerala University",
  "MG University Kerala"
];

export const degrees = [
  // Engineering & Tech
  "B.Tech (Bachelor of Technology)",
  "B.E. (Bachelor of Engineering)",
  "M.Tech (Concentrated Master of Technology)",
  "M.E. (Master of Engineering)",
  "Diploma in Engineering (Polytechnic)",
  
  // Computer Applications
  "BCA (Bachelor of Computer Applications)",
  "MCA (Master of Computer Applications)",
  
  // Medical & Paramedical
  "MBBS (Bachelor of Medicine, Bachelor of Surgery)",
  "BDS (Bachelor of Dental Surgery)",
  "BAMS (Bachelor of Ayurvedic Medicine and Surgery)",
  "BHMS (Bachelor of Homeopathic Medicine and Surgery)",
  "BPT (Bachelor of Physiotherapy)",
  "B.Sc Nursing",
  "GNM (General Nursing and Midwifery)",
  "B.Pharm (Bachelor of Pharmacy)",
  "M.Pharm (Master of Pharmacy)",
  
  // Commerce & Finance
  "B.Com (Bachelor of Commerce)",
  "M.Com (Master of Commerce)",
  "CA Aspirant (Chartered Accountancy)",
  "CS Aspirant (Company Secretary)",
  "CMA Aspirant (Cost and Management Accountancy)",
  
  // Management
  "BBA (Bachelor of Business Administration)",
  "MBA (Master of Business Administration)",
  "PGDM (Post Graduate Diploma in Management)",
  
  // Science
  "B.Sc (Bachelor of Science)",
  "M.Sc (Master of Science)",
  
  // Arts & Humanities
  "B.A. (Bachelor of Arts)",
  "M.A. (Master of Arts)",
  
  // Law
  "LLB (Bachelor of Laws)",
  "BA LLB (Integrated Bachelor of Arts & Laws)",
  "BBA LLB (Integrated Bachelor of Business Admin & Laws)",
  "LLM (Master of Laws)",
  
  // Design
  "B.Des (Bachelor of Design)",
  "M.Des (Master of Design)",
  "Fashion Design Certificate/Degree",
  "Interior Design Certificate/Degree",
  
  // Agriculture
  "B.Sc Agriculture",
  "M.Sc Agriculture",
  "BVSc (Bachelor of Veterinary Science)",
  
  // Education
  "B.Ed (Bachelor of Education)",
  "M.Ed (Master of Education)",
  
  // Government Exams Prep
  "UPSC Prep (Union Public Service Commission)",
  "SSC Prep (Staff Selection Commission)",
  "Banking Exams Prep (IBPS/SBI)",
  "Railways Exams Prep (RRB)",
  "Defence Exams Prep (NDA/CDS/AFC)",
  "State PSC Prep (Public Service Commission)"
];

export const specializations = [
  "Computer Science & Engineering",
  "Information Technology",
  "Artificial Intelligence & Machine Learning (AI & ML)",
  "Data Science",
  "Cyber Security",
  "Cloud Computing",
  "Software Engineering",
  "Electronics & Communication Engineering",
  "Electrical & Electronics Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Biotechnology",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Automobile Engineering",
  "General Management",
  "Finance & Investment Banking",
  "Marketing & Digital Media",
  "Human Resource Management (HR)",
  "Operations & Supply Chain Management",
  "Clinical Psychology",
  "Applied Economics",
  "Political Science",
  "English Literature",
  "Modern History",
  "Sociology & Social Work",
  "Journalism & Mass Communication",
  "General Medicine (MBBS)",
  "General Surgery (MBBS)",
  "Oral & Maxillofacial Surgery (BDS)",
  "Pharmaceutics",
  "Pharmacology",
  "Cardiovascular Physiotherapy",
  "Pediatric Nursing",
  "Corporate Law",
  "Criminal Law",
  "Intellectual Property Law",
  "UX/UI Design",
  "Graphic Design",
  "Interaction Design",
  "Agronomy (Agriculture)",
  "Horticulture",
  "Veterinary Medicine"
];
