// src/utils/collegeData.ts

export const statesAndUTs = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Chandigarh",
  "Puducherry",
  "Jammu & Kashmir",
  "Ladakh",
  "Andaman & Nicobar Islands",
  "Dadra & Nagar Haveli and Daman & Diu",
  "Lakshadweep"
];

// Top cities per state for autocomplete
export const citiesByState: Record<string, string[]> = {
  "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Tirupati", "Kakinada", "Rajahmundry", "Kurnool", "Nellore"],
  "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro"],
  "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tinsukia", "Tezpur", "Bongaigaon"],
  "Bihar": ["Patna", "Gaya", "Muzaffarpur", "Bhagalpur", "Darbhanga", "Purnia", "Ara", "Begusarai"],
  "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Rajnandgaon", "Durg", "Jagdalpur"],
  "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
  "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Anand"],
  "Haryana": ["Faridabad", "Gurugram", "Panipat", "Ambala", "Hisar", "Rohtak", "Karnal", "Sonipat"],
  "Himachal Pradesh": ["Shimla", "Manali", "Dharamsala", "Solan", "Mandi", "Hamirpur", "Kullu"],
  "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh", "Deoghar", "Giridih"],
  "Karnataka": ["Bangalore", "Mysore", "Mangalore", "Hubli", "Belgaum", "Dharwad", "Gulbarga", "Tumkur"],
  "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Palakkad", "Alappuzha", "Kannur"],
  "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Rewa", "Satna"],
  "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Thane", "Kolhapur", "Solapur", "Amravati"],
  "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Senapati"],
  "Meghalaya": ["Shillong", "Tura", "Jowai", "Nongstoin"],
  "Mizoram": ["Aizawl", "Lunglei", "Champhai", "Kolasib"],
  "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Wokha"],
  "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Brahmapur", "Sambalpur", "Puri", "Balasore"],
  "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Pathankot"],
  "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner", "Ajmer", "Alwar", "Bharatpur"],
  "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Mangan"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Vellore", "Tirunelveli", "Erode"],
  "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar", "Secunderabad", "Ramagundam"],
  "Tripura": ["Agartala", "Dharmanagar", "Udaipur", "Kailasahar", "Belonia"],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Prayagraj", "Meerut", "Noida", "Ghaziabad", "Aligarh"],
  "Uttarakhand": ["Dehradun", "Haridwar", "Rishikesh", "Nainital", "Roorkee", "Haldwani", "Mussoorie"],
  "West Bengal": ["Kolkata", "Asansol", "Siliguri", "Durgapur", "Howrah", "Bardhaman", "Kalyani", "Kharagpur"],
  "Delhi": ["New Delhi", "Dwarka", "Rohini", "Pitampura", "Lajpat Nagar", "Janakpuri", "Saket"],
  "Chandigarh": ["Chandigarh", "Mohali", "Panchkula"],
  "Puducherry": ["Puducherry", "Karaikal", "Mahé", "Yanam"],
  "Jammu & Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Sopore", "Udhampur"],
  "Ladakh": ["Leh", "Kargil"],
  "Andaman & Nicobar Islands": ["Port Blair"],
  "Dadra & Nagar Haveli and Daman & Diu": ["Silvassa", "Daman", "Diu"],
  "Lakshadweep": ["Kavaratti", "Agatti", "Minicoy"]
};

export const popularColleges = [
  "IIT Bombay (Indian Institute of Technology)",
  "IIT Delhi (Indian Institute of Technology)",
  "IIT Madras (Indian Institute of Technology)",
  "IIT Kharagpur (Indian Institute of Technology)",
  "IIT Kanpur (Indian Institute of Technology)",
  "IIT Roorkee (Indian Institute of Technology)",
  "IIT Guwahati (Indian Institute of Technology)",
  "IIT Hyderabad (Indian Institute of Technology)",
  "IIT BHU (Varanasi)",
  "IIT Patna",
  "IIT Indore",
  "IIT Mandi",
  "IIT Jodhpur",
  "IIT Gandhinagar",
  "IIT Bhubaneswar",
  "NIT Trichy (National Institute of Technology)",
  "NIT Surathkal (National Institute of Technology)",
  "NIT Rourkela (National Institute of Technology)",
  "NIT Warangal (National Institute of Technology)",
  "NIT Calicut (National Institute of Technology)",
  "NIT Nagpur (VNIT)",
  "NIT Kurukshetra",
  "NIT Jaipur (MNIT)",
  "NIT Allahabad (MNNIT)",
  "NIT Silchar",
  "NIT Durgapur",
  "IIIT Allahabad (Indian Institute of Information Technology)",
  "IIIT Gwalior (Indian Institute of Information Technology)",
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Delhi",
  "BITS Pilani (Birla Institute of Technology and Science)",
  "BITS Goa",
  "BITS Hyderabad",
  "VIT Vellore (Vellore Institute of Technology)",
  "VIT Chennai",
  "VIT Bhopal",
  "VIT AP",
  "SRM Institute of Science and Technology (Chennai)",
  "SRM Kattankulathur",
  "SRM Amaravati",
  "Christ University (Bangalore)",
  "Jain University (Bangalore)",
  "Presidency University (Bangalore)",
  "Manipal Academy of Higher Education (MAHE)",
  "Lovely Professional University (LPU)",
  "Amity University (Noida)",
  "Amity University (Mumbai)",
  "Amity University (Jaipur)",
  "KIIT University (Kalinga Institute of Industrial Technology)",
  "UPES Dehradun",
  "Thapar Institute of Engineering and Technology",
  "Symbiosis International University",
  "NMIMS University (Mumbai)",
  "Bennett University (Greater Noida)",
  "Shiv Nadar University",
  "Ashoka University",
  "Chandigarh University",
  "Graphic Era University",
  "DIT University",
  "Delhi University (DU) - St. Stephen's College",
  "Delhi University (DU) - Hindu College",
  "Delhi University (DU) - Miranda House",
  "Delhi University (DU) - Hansraj College",
  "Delhi University (DU) - Shri Ram College of Commerce (SRCC)",
  "LSR (Lady Shri Ram College for Women)",
  "Ramjas College (DU)",
  "Kirori Mal College (DU)",
  "Presidency College (Chennai)",
  "Presidency College (Kolkata)",
  "Jadavpur University",
  "Calcutta University",
  "Fergusson College (Pune)",
  "Gargi College (DU)",
  "Venkateshwara College (DU)",
  "Atma Ram Sanatan Dharma College (DU)",
  "AIIMS New Delhi (All India Institute of Medical Sciences)",
  "AIIMS Rishikesh",
  "AIIMS Bhubaneswar",
  "AIIMS Bhopal",
  "AIIMS Nagpur",
  "JIPMER Puducherry",
  "Maulana Azad Medical College (Delhi)",
  "Grant Medical College (Mumbai)",
  "King George's Medical University (KGMU)",
  "Kasturba Medical College (Manipal)",
  "Stanley Medical College (Chennai)",
  "National Law School of India University (NLSIU Bangalore)",
  "NALSAR University of Law (Hyderabad)",
  "National Law University (NLU Delhi)",
  "National Law University (NLU Jodhpur)",
  "Government Law College (Mumbai)",
  "National Institute of Design (NID Ahmedabad)",
  "National Institute of Fashion Technology (NIFT Delhi)",
  "NIFT Mumbai",
  "NIFT Hyderabad",
  "Symbiosis Institute of Design (SID Pune)",
  "Xavier's College (Mumbai)",
  "Loyola College (Chennai)",
  "St. Xavier's College (Kolkata)",
  "MCC College (Chennai)",
  "Madras Christian College (Chennai)",
  "Stella Maris College (Chennai)",
  "Bethany Womens College (Bangalore)",
  "R.V. College of Engineering (Bangalore)",
  "B.M.S. College of Engineering (Bangalore)",
  "Dayananda Sagar College of Engineering (Bangalore)",
  "PES University (Bangalore)",
  "M.S. Ramaiah Institute of Technology (Bangalore)",
  "Pune Institute of Computer Technology (PICT)",
  "College of Engineering Pune (COEP)",
  "Veermata Jijabai Technological Institute (VJTI Mumbai)",
  "Fr. Conceicao Rodrigues College of Engineering (Mumbai)",
  "Government College of Engineering (GCEK, Karad)",
  "PSG College of Technology (Coimbatore)",
  "Thiagarajar College of Engineering (TCE Madurai)",
  "Coimbatore Institute of Technology (CIT)",
  "Sri Venkateswara College of Engineering (SVCE)",
  "RMK Engineering College",
  "Andhra Loyola College (Vijayawada)",
  "KL University (Vijayawada)",
  "GITAM University (Visakhapatnam)",
  "Vignan University",
  "Osmania University College (Hyderabad)",
  "Vasavi College of Engineering (Hyderabad)",
  "Chaitanya Bharathi Institute of Technology (CBIT Hyderabad)",
  "Muffakham Jah College of Engineering (Hyderabad)",
  "Nizam College (Hyderabad)"
];

export const popularUniversities = [
  "Central Board of Secondary Education (CBSE)",
  "Delhi University (DU)",
  "Jawaharlal Nehru University (JNU)",
  "Banaras Hindu University (BHU)",
  "Aligarh Muslim University (AMU)",
  "Jamia Millia Islamia",
  "Indraprastha University (GGSIPU)",
  "Visva-Bharati University",
  "University of Mumbai",
  "Savitribai Phule Pune University",
  "University of Calcutta",
  "Jadavpur University",
  "Presidency University (Kolkata)",
  "Anna University",
  "Bharathiar University",
  "University of Madras",
  "Madurai Kamaraj University",
  "Alagappa University",
  "Annamalai University",
  "Periyar University",
  "VTU (Visvesvaraya Technological University)",
  "Bangalore University",
  "Mysore University",
  "Kuvempu University",
  "Tumkur University",
  "JNTU Hyderabad (Jawaharlal Nehru Technological University)",
  "JNTU Anantapur",
  "JNTU Kakinada",
  "Osmania University",
  "Andhra University",
  "Sri Venkateswara University",
  "Krishna University",
  "Nagarjuna University",
  "AKTU Lucknow (Dr. A.P.J. Abdul Kalam Technical University)",
  "Lucknow University",
  "Agra University (Dr. Bhimrao Ambedkar University)",
  "Chaudhary Charan Singh University (CCS Meerut)",
  "BHU Varanasi",
  "Biju Patnaik University of Technology (BPUT)",
  "Utkal University",
  "Sambalpur University",
  "Rajasthan Technical University (RTU)",
  "University of Rajasthan",
  "Jai Narain Vyas University (JNVU Jodhpur)",
  "Mohanlal Sukhadia University (Udaipur)",
  "Gujarat Technological University (GTU)",
  "Saurashtra University",
  "South Gujarat University (Veer Narmad)",
  "MS University Baroda (The Maharaja Sayajirao University)",
  "Hemchandracharya North Gujarat University",
  "Punjab Technical University (PTU)",
  "Panjab University",
  "Guru Nanak Dev University (GNDU)",
  "Guru Gobind Singh Indraprastha University (Delhi)",
  "Kurukshetra University",
  "Maharshi Dayanand University (MDU Rohtak)",
  "Deenbandhu Chhotu Ram University of Science & Technology",
  "Himachal Pradesh University",
  "HP Technical University",
  "Calicut University",
  "Kerala University",
  "MG University Kerala (Mahatma Gandhi University)",
  "Kannur University",
  "CUSAT (Cochin University of Science and Technology)",
  "Madhya Pradesh Bhoj Open University",
  "Barkatullah University (Bhopal)",
  "Devi Ahilya Vishwavidyalaya (Indore)",
  "Rani Durgavati Vishwavidyalaya (Jabalpur)",
  "Jiwaji University (Gwalior)",
  "Gauhati University",
  "Dibrugarh University",
  "Tezpur University",
  "Cotton University (Guwahati)",
  "Guwahati University",
  "Ranchi University",
  "Vinoba Bhave University (Hazaribagh)",
  "Jharkhand Rai University",
  "Magadh University",
  "Patna University",
  "L.N. Mithila University (Darbhanga)",
  "B.R. Ambedkar Bihar University",
  "Chhattisgarh Swami Vivekanand Technical University (CSVTU)",
  "Pt. Ravishankar Shukla University (Raipur)",
  "Goa University",
  "Manipur University",
  "North Eastern Hill University (NEHU)",
  "Assam University (Silchar)",
  "Tripura University",
  "Nagaland University",
  "Mizoram University",
  "Sikkim University",
  "University of Jammu",
  "University of Kashmir",
  "Central University of Rajasthan",
  "Central University of Punjab",
  "Central University of Karnataka",
  "Central University of Himachal Pradesh",
  "Pondicherry University",
  "Hemwati Nandan Bahuguna Garhwal University",
  "Kumaun University"
];

export const degrees = [
  // Engineering & Tech
  "B.Tech (Bachelor of Technology)",
  "B.E. (Bachelor of Engineering)",
  "M.Tech (Concentrated Master of Technology)",
  "M.E. (Master of Engineering)",
  "Diploma in Engineering (Polytechnic)",
  
  // Computer Applications
  "BCA (Bachelor of Computer Applications)",
  "MCA (Master of Computer Applications)",
  
  // Medical & Paramedical
  "MBBS (Bachelor of Medicine, Bachelor of Surgery)",
  "BDS (Bachelor of Dental Surgery)",
  "BAMS (Bachelor of Ayurvedic Medicine and Surgery)",
  "BHMS (Bachelor of Homeopathic Medicine and Surgery)",
  "BPT (Bachelor of Physiotherapy)",
  "B.Sc Nursing",
  "GNM (General Nursing and Midwifery)",
  "B.Pharm (Bachelor of Pharmacy)",
  "M.Pharm (Master of Pharmacy)",
  
  // Commerce & Finance
  "B.Com (Bachelor of Commerce)",
  "M.Com (Master of Commerce)",
  "CA Aspirant (Chartered Accountancy)",
  "CS Aspirant (Company Secretary)",
  "CMA Aspirant (Cost and Management Accountancy)",
  
  // Management
  "BBA (Bachelor of Business Administration)",
  "MBA (Master of Business Administration)",
  "PGDM (Post Graduate Diploma in Management)",
  
  // Science
  "B.Sc (Bachelor of Science)",
  "M.Sc (Master of Science)",
  
  // Arts & Humanities
  "B.A. (Bachelor of Arts)",
  "M.A. (Master of Arts)",
  
  // Law
  "LLB (Bachelor of Laws)",
  "BA LLB (Integrated Bachelor of Arts & Laws)",
  "BBA LLB (Integrated Bachelor of Business Admin & Laws)",
  "LLM (Master of Laws)",
  
  // Design
  "B.Des (Bachelor of Design)",
  "M.Des (Master of Design)",
  "Fashion Design Certificate/Degree",
  "Interior Design Certificate/Degree",
  
  // Agriculture
  "B.Sc Agriculture",
  "M.Sc Agriculture",
  "BVSc (Bachelor of Veterinary Science)",
  
  // Education
  "B.Ed (Bachelor of Education)",
  "M.Ed (Master of Education)",
  
  // Government Exams Prep
  "UPSC Prep (Union Public Service Commission)",
  "SSC Prep (Staff Selection Commission)",
  "Banking Exams Prep (IBPS/SBI)",
  "Railways Exams Prep (RRB)",
  "Defence Exams Prep (NDA/CDS/AFC)",
  "State PSC Prep (Public Service Commission)"
];

export const specializations = [
  "Computer Science & Engineering",
  "Information Technology",
  "Artificial Intelligence & Machine Learning (AI & ML)",
  "Data Science",
  "Cyber Security",
  "Cloud Computing",
  "Software Engineering",
  "Electronics & Communication Engineering",
  "Electrical & Electronics Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Biotechnology",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Automobile Engineering",
  "General Management",
  "Finance & Investment Banking",
  "Marketing & Digital Media",
  "Human Resource Management (HR)",
  "Operations & Supply Chain Management",
  "Clinical Psychology",
  "Applied Economics",
  "Political Science",
  "English Literature",
  "Modern History",
  "Sociology & Social Work",
  "Journalism & Mass Communication",
  "General Medicine (MBBS)",
  "General Surgery (MBBS)",
  "Oral & Maxillofacial Surgery (BDS)",
  "Pharmaceutics",
  "Pharmacology",
  "Cardiovascular Physiotherapy",
  "Pediatric Nursing",
  "Corporate Law",
  "Criminal Law",
  "Intellectual Property Law",
  "UX/UI Design",
  "Graphic Design",
  "Interaction Design",
  "Agronomy (Agriculture)",
  "Horticulture",
  "Veterinary Medicine"
];
